### ISSUE TITLE
Sane defaults for MemSpecLimit and SelectTypeParameters

### ISSUE THREAD

**Issue by jamesbeedy** [charmed-hpc/slurm-charms#36]
### Bug Description

charmed-hpc should prevent jobs from exhausting all memory on the system by default.

1) Currently, job allocations can exhaust all available memory on the system. Set `MemSpecLimit=1024` to ensure systems always have 1G available memory that jobs cannot consume.

2) The slurm configuration provided by the slurm charms does not enforce memory limits on job allocations. Set `SelectTypeParameters=CR_CPU_Memory` to enable slurm + cgroup memory allocation enforcement. 

OPT_CR_CPU_Memory -> https://slurm.schedmd.com/slurm.conf.html#OPT_CR_CPU_Memory

MemSpecLimit -> https://slurm.schedmd.com/slurm.conf.html#OPT_MemSpecLimit

### To Reproduce

NA

### Environment

NA

### Relevant log output

```shell
NA
```

**Comment by NucciTheBoss** [comment]
I agree that we should ensure that at least 1G is free on all the compute nodes so that we don't accidentally kill the daemons we need on the machines. _Nobody likes accidentally taking a node offline..._

We should also enforce memory limits on nodes to prevent there being noisy neighbors on compute nodes.
